name: yxf_habit_tracking_app
description: An example todos app that showcases bloc state management patterns.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^9.0.0
  equatable: ^2.0.0
  flutter_bloc: ^9.1.0
  flutter_inappwebview: ^6.1.5
  intl: ^0.20.2
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2


  local_storage_todos_api:
    path: packages/todo/local_storage_todos_api
  todos_api:
    path: packages/todo/todos_api
  todos_repository:
    path: packages/todo/todos_repository
  tencent_cloud_chat_common:
    path: modules/tencent_cloud_chat_common
  package_info_plus: ^8.3.1
    

dev_dependencies:
  bloc_lint: ^0.3.0
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.6.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true